{{- range $providerName, $providerConfig := .Values.providers }}
{{- if $providerConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $.Release.Name $providerName }}
  labels:
    app.kubernetes.io/name: {{ $providerName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $providerName }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $providerName }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ $providerName }}
          image: {{ $providerConfig.deployment.image }}
          {{- with $providerConfig.deployment.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $providerConfig.deployment.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $providerConfig.service.port }}
              protocol: TCP
          {{- with $providerConfig.persistence.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $providerConfig.persistence.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
