{{- range $providerName, $providerConfig := .Values.providers }}
{{- if $providerConfig.enabled }}
{{- with $providerConfig.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret" $providerName }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ printf "%s-secret" $providerName }}
    template:
      type: Opaque
      engineVersion: v2
      data:
      {{- range .vault.fields }}
        {{ . }}: {{ printf "{{ .%s }}" . | quote }}
      {{- end }}
      {{- with .vault.connectionString }}
        {{ .key }}: {{ .template | quote }}
      {{- end }}
  data:
  {{- range .vault.fields }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ printf "secret/data/hub/%s" $providerName }}
      property: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
