{{- range $providerName, $providerConfig := .Values.providers }}
{{- if $providerConfig.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-populate-%s-job" $.Release.Name $providerName }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      containers:
      - image: {{ $.Values.vectorEmbedJob.image }}
        name: vector-embedder
        env:
          - name: TEMP_DIR
            value: {{ $.Values.vectorEmbedJob.tempDir }}
          - name: LOG_LEVEL
            value: {{ $.Values.vectorEmbedJob.logLevel }}
          - name: REPO_SOURCES
            value: {{ $.Values.vectorEmbedJob.repoSources | toJson | quote }}
          - name: WEB_SOURCES
            value: {{ $.Values.vectorEmbedJob.webSources | toJson | quote }}
          - name: CHUNK_OVERLAP
            value: {{ $.Values.vectorEmbedJob.chunking.overlap | quote }}
          - name: CHUNK_SIZE
            value: {{ $.Values.vectorEmbedJob.chunking.size | quote }}
          - name: DB_TYPE
            value: {{ $providerName | upper }}
          - name: EMBEDDING_MODEL
            value: {{ $.Values.global.embeddingModel }}
        {{- with $providerConfig.jobEnv }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: {{ $.Values.vectorEmbedJob.restartPolicy }}
  backoffLimit: {{ $.Values.vectorEmbedJob.backoffLimit }}
{{- end }}
{{- end }}
