replicaCount: 1

image:
  repository: quay.io/validatedpatterns/rag-llm-demo-ui
  pullPolicy: Always
  tag: latest

env:
  - name: LOG_LEVEL
    value: info
  - name: HOST
    value: 0.0.0.0
  - name: LLM_URLS
    value: '["http://cpu-inference-service-predictor/v1"]'
  - name: DB_PROVIDERS
    value: '[{"type": "qdrant", "collection": "docs", "url": "http://qdrant-service:6333", "embedding_model": "sentence-transformers/all-mpnet-base-v2"}]'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 7860

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
