FROM registry.access.redhat.com/ubi10/python-312-minimal:10.0

USER root

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install \
      --no-cache-dir \
      --compile \
      -r requirements.txt

COPY app.py .

RUN chown -R 1001:0 .
USER 1001

CMD ["python", "./app.py"]
